apiVersion: v1
kind: Service
metadata:
  name: sysinfo-restapp
  namespace: sysinfo-restapp
spec:
  selector:
    app: sysinfo-restapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort